const fs = require('fs');
const path = require('path');

const mdPath = 'references/roadmap_overview_detail.md';
const outputDir = 'app/src/data';
const outputPath = path.join(outputDir, 'searchIndex.ts');
const contentsDir = 'app/src/contents';

if (!fs.existsSync(mdPath)) {
    console.error(`Error: ${mdPath} not found`);
    process.exit(1);
}

const mdContent = fs.readFileSync(mdPath, 'utf8');
const lines = mdContent.split('\n');

const topicMatch = /^### ([\w-]+):/;
const sectionMatch = /^  - (\d+\.\d+):/;

let currentTopicId = null;
const sections = [];

console.log("Parsing roadmap overview...");

for (let line of lines) {
    line = line.trimRight();
    const tm = line.match(topicMatch);
    if (tm) {
        currentTopicId = tm[1];
        continue;
    }

    const sm = line.match(sectionMatch);
    if (sm && currentTopicId) {
        const fullId = sm[1]; // e.g. "1.1"
        const chapterId = fullId.split('.')[0];
        sections.push({
            topicId: currentTopicId,
            chapterId: chapterId,
            sectionId: fullId
        });
    }
}

console.log(`Found ${sections.length} sections. Extracting keywords...`);

const searchIndex = {};

sections.forEach(sec => {
    const topicFormatted = sec.topicId.replace('-', '_');
    const filePath = path.join(contentsDir, `topic${topicFormatted}`, `chapter${sec.chapterId}`, `section${topicFormatted}_${sec.sectionId}.tsx`);
    const key = `${sec.topicId}|${sec.chapterId}|${sec.sectionId}`;
    
    if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');
        const tags = new Set();

        // 1. Extract <b> and <strong>
        const boldRegex = /<(?:b|strong)>([^<]+)<\/(?:b|strong)>/g;
        let match;
        while ((match = boldRegex.exec(content)) !== null) {
            tags.add(match[1].trim());
        }

        // 2. Extract ContentBox titles
        const boxRegex = /title="([^"]+)"/g;
        while ((match = boxRegex.exec(content)) !== null) {
            const title = match[1].trim();
            tags.add(title);
            // Extract text in parentheses if any
            const parenMatch = title.match(/\(([^)]+)\)/);
            if (parenMatch) {
                tags.add(parenMatch[1].trim());
            }
        }

        // 3. Extract h2 and h3
        const headerRegex = /<h[23][^>]*>([^<]+)<\/h[23]>/g;
        while ((match = headerRegex.exec(content)) !== null) {
            tags.add(match[1].trim());
        }

        if (tags.size > 0) {
            searchIndex[key] = Array.from(tags).filter(t => t.length > 1);
        }
    } else {
        // console.warn(`Warning: File not found for ${key}: ${filePath}`);
    }
});

// Generate TypeScript output
const tsOutput = `/**
 * This file is auto-generated by generate_search_index.js
 * Do not edit this file manually.
 */

export const searchIndex: Record<string, string[]> = ${JSON.stringify(searchIndex, null, 4)};
`;

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, tsOutput, 'utf8');
console.log(`Successfully generated search index at ${outputPath}`);
console.log(`Total sections indexed: ${Object.keys(searchIndex).length}`);
