[build]
  command = "cd app && npm install && npm run build"
  publish = "app/dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=8192"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
