[build]
  command = "cd app && npm install && npm run build"
  publish = "app/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/assets/*"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
