import { BlockMath, InlineMath } from 'react-katex';
import 'katex/dist/katex.min.css';
import ContentBox from '../../../components/content/ContentBox';

export default function GeneratedIdeals() {
    return (
        <section className="prose prose-slate dark:prose-invert max-w-none text-slate-800 dark:text-slate-200">
            <p>
                イデアルは、いくつかの要素から「生成する」ことができます。これは線形代数において、いくつかのベクトルから「張られる部分空間」を作ったのと同じ発想です。本節では、環の要素からイデアルを作り出す方法と、イデアル同士の演算について学びます。なお、本節以降、環 <InlineMath math="R" /> はとくに断らない限り<b>可換環</b>であるとします。
            </p>

            <hr className="my-8 border-slate-200 dark:border-slate-700" />

            <h2 className="text-2xl font-bold mt-8 mb-6">生成されたイデアルと主イデアル</h2>

            <ContentBox type="definition" title="Definition 2.2-1 (生成されたイデアル)">
                <p>
                    可換環 <InlineMath math="R" /> とその要素 <InlineMath math="a_1, a_2, \dots, a_n \in R" /> を考える。これらを用いて
                </p>
                <BlockMath math="\begin{aligned} &(a_1, a_2, \dots, a_n) \\ &= \{ r_1 a_1 + r_2 a_2 + \dots + r_n a_n \mid r_1, r_2, \dots, r_n \in R \} \end{aligned}" />
                <p>
                    と定義される集合は <InlineMath math="R" /> のイデアルとなる。これを <InlineMath math="a_1, \dots, a_n" /> によって<b>生成されたイデアル（ideal generated by）</b>という。
                </p>
                <p>
                    とくに、ただ 1 つの要素 <InlineMath math="a" /> によって生成されるイデアルを<b>主イデアル（principal ideal）</b>と呼び、<InlineMath math="(a)" /> や <InlineMath math="aR" /> と書く。
                </p>
                <BlockMath math="(a) = aR = \{ ra \mid r \in R \}" />
            </ContentBox>

            <p>
                「張られる」という言葉を使うと、<InlineMath math="(a_1, a_2)" /> は「<InlineMath math="a_1" /> と <InlineMath math="a_2" /> をベースとして、環のすべての要素を掛けて足し合わせたもの（線形結合の全体）」と言えます。
            </p>

            <ContentBox type="proposition" title="Proposition 2.2-1 (生成されたイデアルの最小性)">
                <p>
                    <InlineMath math="(a_1, \dots, a_n)" /> は、<InlineMath math="a_1, \dots, a_n" /> をすべて含む <InlineMath math="R" /> のイデアルの中で<b>最小のもの</b>である。すなわち、<InlineMath math="a_1, \dots, a_n" /> を含む任意のイデアル <InlineMath math="I" /> に対して、<InlineMath math="(a_1, \dots, a_n) \subset I" /> が成り立つ。
                </p>
            </ContentBox>

            <ContentBox type="proof" title="Proof">
                <p>
                    <InlineMath math="I" /> が <InlineMath math="a_1, \dots, a_n" /> を含むイデアルであるとする。<br />
                    イデアルの吸収律より、任意の <InlineMath math="r_i \in R" /> に対して <InlineMath math="r_i a_i \in I" /> である。<br />
                    さらに、イデアルは加法について閉じている（部分群である）ため、それらの和 <InlineMath math="r_1 a_1 + \dots + r_n a_n" /> も <InlineMath math="I" /> に含まれる。<br />
                    これは <InlineMath math="(a_1, \dots, a_n)" /> の任意の元が <InlineMath math="I" /> に含まれることを意味するので、<InlineMath math="(a_1, \dots, a_n) \subset I" /> である。
                </p>
                <div className="text-right text-slate-500 dark:text-slate-400">
                    <InlineMath math="\square" />
                </div>
            </ContentBox>

            <ContentBox type="example" title="Example 2.2-1 (整数環におけるイデアル)">
                <p>
                    整数環 <InlineMath math="\mathbb{Z}" /> におけるイデアルを考えてみましょう。
                </p>
                <p>
                    <b>主イデアル：</b><br />
                    <InlineMath math="3" /> によって生成される主イデアルは <InlineMath math="(3) = \{ 3r \mid r \in \mathbb{Z} \} = 3\mathbb{Z}" /> となり、これは 3 の倍数全体です。
                </p>
                <p>
                    <b>2つの元から生成されるイデアル：</b><br />
                    <InlineMath math="(4, 6)" /> というイデアルを考えます。定義によれば
                    <BlockMath math="(4, 6) = \{ 4x + 6y \mid x, y \in \mathbb{Z} \}" />
                    です。整数論の「ベズーの等式（一次不定方程式）」を思い出すと、<InlineMath math="4x + 6y" /> の形で表せる整数は、<InlineMath math="4" /> と <InlineMath math="6" /> の最大公約数である <InlineMath math="2" /> の倍数全体に一致します。したがって、
                    <BlockMath math="(4, 6) = (2)" />
                    となります。2つの元で生成したように見えて、実は 1つの元 <InlineMath math="2" /> だけで生成される主イデアルと同じものでした。
                </p>
            </ContentBox>

            <p>
                実は、<InlineMath math="\mathbb{Z}" /> のイデアルは<b>すべて主イデアル</b>になるという強力な性質を持っています（第6章「単項イデアル整域」で詳しく学びます）。多項式環 <InlineMath math="\mathbb{R}[x, y]" /> などの複雑な環では、1つの元では生成しきれないイデアル（例：<InlineMath math="(x, y)" />）が存在します。
            </p>

            <hr className="my-8 border-slate-200 dark:border-slate-700" />

            <h2 className="text-2xl font-bold mt-8 mb-6">イデアルの演算</h2>

            <p>
                イデアル同士を足したり掛けたりして、新しいイデアルを作ることができます。
            </p>

            <ContentBox type="definition" title="Definition 2.2-2 (イデアルの和と積)">
                <p>
                    可換環 <InlineMath math="R" /> の 2 つのイデアル <InlineMath math="I, J" /> に対して、和と積を以下のように定義する。
                </p>
                <ul className="list-disc list-inside space-y-4 mt-2">
                    <li>
                        <b>和（Sum）：</b>
                        <BlockMath math="I + J = \{ a + b \mid a \in I, b \in J \}" />
                        これは <InlineMath math="I \cup J" /> を含む最小のイデアルである。
                    </li>
                    <li>
                        <b>積（Product）：</b>
                        <BlockMath math="IJ = \left\{ \sum_{k=1}^n a_k b_k \;\middle|\; a_k \in I, b_k \in J, n \geq 1 \right\}" />
                        単なる要素同士の積 <InlineMath math="ab" /> を集めた集合 <InlineMath math="\{ab \mid a \in I, b \in J\}" /> は加法で閉じていないため、それらの<b>有限和</b>をとる必要がある。
                    </li>
                    <li>
                        <b>共通部分（Intersection）：</b>
                        <BlockMath math="I \cap J = \{ x \mid x \in I \text{ かつ } x \in J \}" />
                    </li>
                </ul>
                <p className="mt-2">
                    これら <InlineMath math="I+J, IJ, I\cap J" /> はすべて <InlineMath math="R" /> のイデアルとなる。（※和集合 <InlineMath math="I \cup J" /> は一般にイデアルにならないことに注意）
                </p>
            </ContentBox>

            <p>
                イデアルの演算には、以下のような包含関係が常に成り立ちます。
            </p>
            <BlockMath math="IJ \subset I \cap J \subset I \subset I+J" />
            <BlockMath math="IJ \subset I \cap J \subset J \subset I+J" />

            <ContentBox type="example" title="Example 2.2-2 (Z におけるイデアルの演算)">
                <p>
                    整数環 <InlineMath math="\mathbb{Z}" /> において、<InlineMath math="I = (4)" />、<InlineMath math="J = (6)" /> とします。
                </p>
                <ul className="list-disc list-inside space-y-2 mt-2">
                    <li><b>和 <InlineMath math="I + J" />：</b> <InlineMath math="4" /> の倍数と <InlineMath math="6" /> の倍数を足して作れる数。これは最大公約数 <InlineMath math="2" /> の倍数なので、<InlineMath math="(4) + (6) = (2)" />。<br />（一般に <InlineMath math="(a) + (b) = (\gcd(a,b))" />）</li>
                    <li><b>共通部分 <InlineMath math="I \cap J" />：</b> <InlineMath math="4" /> の倍数かつ <InlineMath math="6" /> の倍数。これは最小公倍数 <InlineMath math="12" /> の倍数なので、<InlineMath math="(4) \cap (6) = (12)" />。<br />（一般に <InlineMath math="(a) \cap (b) = (\mathrm{lcm}(a,b))" />）</li>
                    <li><b>積 <InlineMath math="IJ" />：</b> <InlineMath math="4a \cdot 6b = 24ab" /> の和で表される数。よって <InlineMath math="(4)(6) = (24)" />。<br />（一般に <InlineMath math="(a)(b) = (ab)" />）</li>
                </ul>
                <p>
                    包含関係を確認すると、<InlineMath math="(24) \subset (12) \subset (4) \subset (2)" /> となっており、確かに <InlineMath math="IJ \subset I \cap J \subset I \subset I+J" /> を満たしています。
                </p>
            </ContentBox>

            <ContentBox type="note" title="§2.2 のまとめ">
                <ul className="list-disc list-inside space-y-1">
                    <li><InlineMath math="(a_1, \dots, a_n)" /> は、与えられた元から作られる線形結合の全体であり、それらを含む最小のイデアルである。</li>
                    <li>1つの元 <InlineMath math="a" /> だけで生成されるイデアル <InlineMath math="(a)" /> を<b>主イデアル</b>と呼ぶ。</li>
                    <li>イデアル同士は、和 <InlineMath math="I+J" />、積 <InlineMath math="IJ" />、共通部分 <InlineMath math="I \cap J" /> という演算によって新しいイデアルを作ることができ、<InlineMath math="IJ \subset I \cap J \subset I, J \subset I+J" /> の関係がある。</li>
                </ul>
            </ContentBox>
        </section>
    );
}